### ISSUE TITLE
Remove vestigial `NodeTo*Version` constructors

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/ouroboros-network#3129]
Now that `mainnet` is in the Mary era, we need not successfully connect to peers that can't participate in the Mary era. Thus we can simplify the code by removing those older negotiable versions and whatever backwards-compatibility logic they've been carrying along in eg our serializers.

cc @coot

**Comment by dnadales** [comment]
Should we duplicate this issue in `ouroboros-consensus`?

**Comment by nfrisby** [comment]
I don't think we need to duplicate this issue, since the integration of whichever `ouroboros-network` version includes this change will force the dead code to be reaped etc.

**Comment by nfrisby** [comment]
@coot I removed the consensus labels---despite me opening it, this is a proper `networking` Issue, I think.

**Comment by amesgen** [comment]
Old NodeToNode versions were removed in #4985

What about also removing old NodeToClient versions?

**Comment by coot** [comment]
@amesgen do you have an advise which versions should be removed?

**Comment by amesgen** [comment]
Node 9.0.0/9.1.0 use `latestReleasedNodeVersion = NodeToClientV_16` ([src](https://github.com/IntersectMBO/ouroboros-consensus/blob/release-ouroboros-consensus-cardano-0.18.0.0/ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Node.hs#L487)), and as every node must have upgraded to at least this version since Conway, we could remove everything below `NodeToClientV_16`.
