### ISSUE TITLE
PeerSharingServer refactorisation

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-network#4782]
[`computePeerSharing`](https://github.com/IntersectMBO/ouroboros-network/blob/master/ouroboros-network/src/Ouroboros/Network/Diffusion/P2P.hs#L1220-L1236) should be defined in  `Ouroboros.Network.PeerSharing`.  We don't need to export it, it should be used directly by [`peerSharingServer`](https://github.com/IntersectMBO/ouroboros-network/blob/master/ouroboros-network/src/Ouroboros/Network/PeerSharing.hs#L96-L103).  This will simplify the interface we expose to consensus, e.g. no callback in the `daApplicationInitiatorResponderMode`, but instead requires access to `PublicPeerSelectionState` which is fine, we do that for other mini-protocols as well.  Ideally `daApplicationIntiatorResponderMode` wouldn't it as an argument, other protocols don't need to pass similar information if I recall correctly.

**Comment by bolt12** [comment]
IIRC it is only how it is now because polymorphism shenanigans and because we need access to the `PeerSelectionState`. Since `peerSharingServer` is used in consensus code when setting up the miniprotocols and since we need access to PeerSelectionState, we have to partially apply `computePeerSharingServer` which is defined in ouroboros-network `Diffusion.P2P` (module that has access to `PeerSelectionState`) to `daApplicationInitiatorResponderMode`.

If we want to move `computePeerSharing` to `Ouroboros.Network.PeerSharing` and call it directly in `peerSharingServer` we still need a way to pass an STM action to read the PeerSelectionState to consensus. So maybe the cleanest way to do this is to define a PeerSharing consensus API dictionary and use that

**Comment by coot** [comment]
We can pass `TVar PublicPeerSelectionState` to `Diffusion` through `DiffusionArguments` (even better just pass `atomically . writeTVar publicPeerSelectionStateVar :: PublickPeerSelectionState -> m ()` - this requires some changes, but it's possible).  Then we will have access to the `TVar` outside of `Diffusion` and thus allow us to create `peerSharingServer` outside of the diffusion context, it will be responsibility of `consensus` to create the `TVar` and pass it to the right places.  This is already true for other mini-protocols, that they create some context outside of `diffusion`, e.g. the `bracketSyncWithFetchClient` requires `FetchClientRegistry` which is part of [`NodeKernel`](https://github.com/intersectmbo/ouroboros-consensus/blob/fb68484e44fbd12ba4a82852e7e54d22e3f3234f/ouroboros-consensus-diffusion/src/ouroboros-consensus-diffusion/Ouroboros/Consensus/NodeKernel.hs#L106), maybe that's the right place for the `TVar` too.
